name: telegram message
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          photo: assets/icon.png
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            👤 [${{ github.actor }}](https://github.com/${{ github.actor }}) захуячил пуш в мастер! [Посмотреть изменения](https://github.com/${{ github.repository }}/commit/${{github.sha}})
